from unittest.mock import patch, MagicMock
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.db.database import Base
from app.models.ai_cache import AICache
from app.schemas.learning import LearningRequest
from app.services.learning_service import (
    generate_learning_content,
    search_topics,
)


def test_topic_search_filtering():
    """
    Verifies topic search by title, slug, and partial matches across catalog.
    """
    engine = create_engine("sqlite:///:memory:")
    Base.metadata.create_all(bind=engine)
    TestingSession = sessionmaker(bind=engine)
    db = TestingSession()

    # Search specific topic
    res_py = search_topics("Python", db=db)
    assert len(res_py.results) > 0
    assert any("python" in c.title.lower() for c in res_py.results)

    # Search slug match
    res_docker = search_topics("docker-containerization", db=db)
    assert len(res_docker.results) > 0
    assert any("docker" in c.title.lower() for c in res_docker.results)

    # Search partial match
    res_sql = search_topics("sql", db=db)
    assert len(res_sql.results) > 0


def test_ai_cache_hit_and_miss_flow():
    """
    Verifies the complete AI Cache lifecycle:
    1. First call -> Cache miss -> Generates via Gemini provider -> Persists in AICache DB with cached=False.
    2. Second call -> Cache hit -> Returns instantly from DB with cached=True without invoking Gemini.
    """
    engine = create_engine("sqlite:///:memory:")
    Base.metadata.create_all(bind=engine)
    TestingSession = sessionmaker(bind=engine)
    db = TestingSession()

    mock_lesson_json = """
    {
      "topic": "FastAPI",
      "why_learn_this": "FastAPI provides modern, fast web APIs in Python.",
      "professional_definition": "An asynchronous Python web framework built on Starlette and Pydantic.",
      "easy_explanation": "A super fast tool to build website backends easily.",
      "real_world_analogy": "Like a high-speed express train station.",
      "real_world_applications": ["Microservices", "REST APIs", "AI Services"],
      "syntax_or_core_concepts": "@app.get('/')\\ndef root():\\n    return {'msg': 'Hello'}",
      "examples": [
        {"title": "Basic Route", "explanation": "Simple endpoint", "code": "print('hello')"}
      ],
      "common_mistakes": ["Blocking I/O in async def routes"],
      "interactive_practice": [
        {"question": "Create a GET route", "hint": "Use @app.get decorator"}
      ],
      "quiz": [
        {
          "question": "What library does FastAPI use for data validation?",
          "options": ["Pydantic", "Marshmallow", "Cerberus", "Schema"],
          "answer": "Pydantic",
          "explanation": "FastAPI relies on Pydantic models for request parsing and validation."
        },
        {
          "question": "What ASGI server commonly runs FastAPI?",
          "options": ["Uvicorn", "Gunicorn", "Waitress", "Twisted"],
          "answer": "Uvicorn",
          "explanation": "Uvicorn is a lightning-fast ASGI server implementation."
        },
        {
          "question": "What keyword enables asynchronous route handlers?",
          "options": ["async def", "def async", "coroutine", "thread"],
          "answer": "async def",
          "explanation": "FastAPI leverages Python's native async def syntax."
        },
        {
          "question": "What format is automatically generated by FastAPI for API docs?",
          "options": ["OpenAPI / Swagger", "WSDL", "RAML", "SOAP"],
          "answer": "OpenAPI / Swagger",
          "explanation": "FastAPI automatically serves interactive Swagger UI."
        },
        {
          "question": "Which decorator defines a POST endpoint in FastAPI?",
          "options": ["@app.post()", "@app.get()", "@app.put()", "@app.delete()"],
          "answer": "@app.post()",
          "explanation": "POST endpoints are declared via @app.post()."
        }
      ],
      "assignment": {
        "title": "Build a Todo API",
        "description": "Create CRUD endpoints",
        "requirements": ["GET /todos", "POST /todos"]
      },
      "mini_project": {
        "title": "URL Shortener Microservice",
        "description": "Store short codes in SQLite",
        "requirements": ["FastAPI app", "Database model"]
      },
      "related_topics": ["Starlette", "Pydantic", "Uvicorn"],
      "summary": "FastAPI is the standard for high-performance Python backends.",
      "next_topic": "SQLAlchemy with FastAPI"
    }
    """

    req = LearningRequest(topic="FastAPI", language="English", level="beginner")

    # Step 1: Cache Miss -> Call Gemini
    mock_provider = MagicMock()
    mock_provider.generate.return_value = mock_lesson_json

    with patch("app.services.learning_service.GeminiProvider", return_value=mock_provider):
        res_miss = generate_learning_content(req, db=db)
        assert res_miss.cached is False
        assert res_miss.topic == "FastAPI"
        assert len(res_miss.quiz) == 5
        assert mock_provider.generate.call_count == 1

        # Verify entry was saved to DB
        cached_row = db.query(AICache).filter(AICache.cache_key == "fastapi:english:beginner").first()
        assert cached_row is not None
        assert cached_row.topic == "FastAPI"

    # Step 2: Cache Hit -> Gemini is NOT called
    mock_provider_2 = MagicMock()
    with patch("app.services.learning_service.GeminiProvider", return_value=mock_provider_2):
        res_hit = generate_learning_content(req, db=db)
        assert res_hit.cached is True
        assert res_hit.topic == "FastAPI"
        assert len(res_hit.quiz) == 5
        # Gemini should NOT have been called on cache hit
        assert mock_provider_2.generate.call_count == 0
